// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCepnJgsibwzX0VGw0N9wVQH4e4rVAF_ks',
    appId: '1:1009935937244:web:efcf5d2befa9a473158e19',
    messagingSenderId: '1009935937244',
    projectId: 'trip-995d7',
    authDomain: 'trip-995d7.firebaseapp.com',
    databaseURL:
        'https://trip-995d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-995d7.firebasestorage.app',
    measurementId: 'G-F8NL0N8RRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIZN4BRMgLmab4lH-IjQ3TQY7_VJ5oNA',
    appId: '1:1009935937244:android:34175ef7b6230501158e19',
    messagingSenderId: '1009935937244',
    projectId: 'trip-995d7',
    databaseURL:
        'https://trip-995d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-995d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6opc_Cds1u7Oh_JvcX8vPiTtBFrUwPr4',
    appId: '1:1009935937244:ios:6029f2b6c00ca3e6158e19',
    messagingSenderId: '1009935937244',
    projectId: 'trip-995d7',
    databaseURL:
        'https://trip-995d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-995d7.firebasestorage.app',
    iosBundleId: 'com.example.tourn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6opc_Cds1u7Oh_JvcX8vPiTtBFrUwPr4',
    appId: '1:1009935937244:ios:6029f2b6c00ca3e6158e19',
    messagingSenderId: '1009935937244',
    projectId: 'trip-995d7',
    databaseURL:
        'https://trip-995d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-995d7.firebasestorage.app',
    iosBundleId: 'com.example.tourn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCepnJgsibwzX0VGw0N9wVQH4e4rVAF_ks',
    appId: '1:1009935937244:web:8004f26bfdb1af93158e19',
    messagingSenderId: '1009935937244',
    projectId: 'trip-995d7',
    authDomain: 'trip-995d7.firebaseapp.com',
    databaseURL:
        'https://trip-995d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-995d7.firebasestorage.app',
    measurementId: 'G-GS151Z3D45',
  );
}
